[project]
name = "medigap-uw-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "langchain-pinecone>=0.2.13",
]
